name: Build benchmark

on:
  push:

jobs:
  build:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Windows environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{matrix.cmake}}

      - name: Print CMake version
        run: cmake --version

      # Static Debug
      - name: "Run benchmark"
        run: mkdir build && cd build && ../benchmark.sh

      - name: Upload Benchmark Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs_${{ matrix.os }}
          path: build/*.log
